spring:
  application:
    name: TicketService
  datasource:
    #    url: jdbc:postgresql://localhost:5432/ticket_service
    #    username: postgres
    #    password: "Welcome@1234"
    #    driver-class-name: org.postgresql.Driver
    
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8082
  #eureka:
  #  client:
  #    service-url:
  #        defaultZone: http://localhost:8761/eureka

  #camel:
  #  springboot:
  #   name: ticketService-camel
#debug: false